### PR TITLE
feat: Auth Google Cloud with api keys

### PR DESCRIPTION
**Pull request by AnNguyen98**
Implement Auth Google Cloud with api keys

### CODE REVIEW

**Comment by felixjunghans** [comment]
Hey @AnNguyen98 thanks for your contribution. I will merge it and create a new Version of google_speech soon.

**Review by felixjunghans — APPROVED** [review]

**Comment by NguyenTheAn98** [comment]
@felixjunghans 
Why you add projectId here?
```  /// Creates a SpeechToText interface using a API keys.
  factory SpeechToTextV2.viaApiKey(String apiKey, String projectId) =>
      SpeechToTextV2._(CallOptions(metadata: {'X-goog-api-key': '$apiKey'}),
          projectId: projectId);```

**Comment by NguyenTheAn98** [comment]
@felixjunghans

**Comment by NguyenTheAn98** [comment]
factory SpeechToTextV2.viaApiKey(String apiKey, String projectId) =>
      SpeechToTextV2._(CallOptions(metadata: {'X-goog-api-key': '$apiKey'}));```

**Comment by felixjunghans** [comment]
@AnNguyen98 I added projectId in V2 because it is needed for     

`recognizer: 'projects/$projectId/locations/global/recognizers/_',`

**Comment by NguyenTheAn98** [comment]
@felixjunghans 
Thanks, I saw it in google docs. 
But I have a question, why you don't define full model in RecognitionModel? 
```
latest_long | Best for long form content like media or conversation.
latest_short | Best for short form content like commands or single shot directed speech.
command_and_search | Best for short queries such as voice commands or voice search.
phone_call | Best for audio that originated from a phone call (typically recorded at an 8khz sampling rate).
video | Best for audio that originated from video or includes multiple speakers. Ideally the audio is recorded at a 16khz or greater sampling rate. This is a premium model that costs more than the standard rate.
default | Best for audio that is not one of the specific audio models. For example, long-form audio. Ideally the audio is high-fidelity, recorded at a 16khz or greater sampling rate.
medical_conversation | Best for audio that originated from a conversation between a medical provider and patient.
medical_dictation | Best for audio that originated from dictation notes by a medical provider.


```

**Comment by felixjunghans** [comment]
I think at the time I created it, some were not yet available. I'll try to update it soon and add the missing ones.

**Comment by AnNguyen98** [comment]
@felixjunghans 
I update model, please help me review this [PR](https://github.com/felixjunghans/google_speech/pull/51)

**Pull request merged**
